Modified the app-init to Handle instances of unhealthy containers.

diff --git a/.github/actions/app-init/action.yml b/.github/actions/app-init/action.yml
--- a/.github/actions/app-init/action.yml
+++ b/.github/actions/app-init/action.yml
@@ -21,13 +21,15 @@ runs:
         docker image ls "$PROJECT_NAME*" --no-trunc
       shell: bash
     # start containers
-    - run: docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME up -d --force-recreate
-      shell: bash
-    # wait for containers to become healthy
     - run: |
+        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME up -d --force-recreate
+        
         i=0
-        while [[ $(docker container ls --filter "status=running" -q) != $(docker container ls --filter "status=running" --filter "health=healthy" -q) ]]
-        do
+        while [[
+          $(docker container ls --filter "status=running" -q) != $(docker container ls --filter "status=running" --filter "health=healthy" -q)
+          &&
+          $(docker container ls --filter "status=running" --filter "health=unhealthy" -q) -eq 0
+        ]]; do
           sleep 1
           i=$((i+1))
           if [[ $(($i % 10)) -eq 0 ]]; then
@@ -35,9 +37,16 @@ runs:
             echo "$(docker container ls --filter "status=running" --filter "health=healthy" -q | wc -l) healthy container(s)"
           fi
         done
-        echo "it took $i seconds for containers to become healthy"
         
-        docker container ls --size --no-trunc
+        unhealthy_count=$(docker container ls --filter "status=running" --filter "health=unhealthy" -q)
+        if [[ $unhealthy_count -eq 0 ]]; then
+          echo "it took $i seconds for containers to become healthy"
+          docker container ls --size --no-trunc
+        else
+          echo "Failing due to $unhealthy_count containers"
+          # force a failure due to unhealthy containers
+          exit 1;
+        fi
       shell: bash
     # ensure correct user:group ownership
     - run: |
